# Generated by Django 4.2.4 on 2023-10-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='emp_id',
            field=models.CharField(max_length=20),
        ),
    ]
